# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install
        run: npm install --ignore-scripts
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip install slither-analyzer==0.8.1 solc-select==0.2.1
      - name: Summary of static ananlysis
        run: |
          slither . --print human-summary
      - name: Contract summary of static ananlysis
        run: |
          slither . --print contract-summary
      - name: Function summary
        run: |
          slither . --print function-summary
      - name: Inheritance
        run: |
          slither . --print inheritance
      - name: Data dependency
        run: |
          slither . --print data-dependency
